
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author MubeenDev
 */
public class UpdateData extends javax.swing.JFrame {

    /**
     * Creates new form UpdateDate
     */
    
    Connection connect=null;
    int id=0;
    
    public UpdateData() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        connectDatabase();
    }
    
    public void connectDatabase(){
        try{
            connect = DriverManager.getConnection("jdbc:mysql://localhost/busticket","root","");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Cannot connect to database");
        }
    }
    
    public void setID(int a){
        id=a;
        getData();
    }
    
    public void getData(){
        ResultSet resultSet = null;
        try{
            String query = "SELECT * FROM ticket WHERE ticketID="+id;
            Statement statement ;
            statement = connect.createStatement();
            resultSet = statement.executeQuery(query);
            if(resultSet.next()){
                jTextField1.setText(resultSet.getInt("passengerID")+"");
                jTextField3.setText(resultSet.getString("seatNumber"));
                jTextField5.setText(resultSet.getString("routeNumber"));
                jTextField8.setText(resultSet.getDouble("price")+"");
                if(resultSet.getString("seatType").toLowerCase().equals("classic")){
                    jComboBox1.setSelectedIndex(1);
                }else if(resultSet.getString("seatType").toLowerCase().equals("economy")){
                    jComboBox1.setSelectedIndex(2);
                }
                jDateChooser1.setDate(resultSet.getDate("issueDate"));
                jDateChooser2.setDate(resultSet.getDate("journeyDate"));
                timePicker1.setText(resultSet.getTime("departureTime").toString());
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<String>();
        jLabel10 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        timePicker1 = new com.github.lgooddatepicker.components.TimePicker();
        jLabel12 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 600));
        setPreferredSize(new java.awt.Dimension(800, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/arrow.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 10, 50, 30);

        jLabel11.setText("Passenger ID:");
        jLabel11.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 255, 204));
        getContentPane().add(jLabel11);
        jLabel11.setBounds(160, 80, 120, 40);

        jTextField1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1);
        jTextField1.setBounds(320, 90, 330, 30);

        jLabel6.setText("Seat Type:");
        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(102, 255, 204));
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 130, 100, 40);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose Seat Type", "Classic", "Economy" }));
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(320, 140, 330, 30);

        jLabel10.setText("Seat Number:");
        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 255, 204));
        getContentPane().add(jLabel10);
        jLabel10.setBounds(160, 190, 120, 30);

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField3);
        jTextField3.setBounds(320, 190, 330, 30);

        jLabel5.setText("Issue Date:");
        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 204));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 240, 120, 40);

        jDateChooser1.setDateFormatString("yyyy-MM-d");
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(320, 240, 330, 30);

        jLabel7.setText("Journey Date:");
        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(102, 255, 204));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(160, 290, 140, 30);

        jDateChooser2.setDateFormatString("yyyy-MM-d");
        getContentPane().add(jDateChooser2);
        jDateChooser2.setBounds(320, 290, 330, 30);

        jLabel4.setText("Departure Time:");
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 255, 204));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 340, 160, 30);
        getContentPane().add(timePicker1);
        timePicker1.setBounds(320, 340, 330, 30);

        jLabel12.setText("Route Number:");
        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 255, 204));
        getContentPane().add(jLabel12);
        jLabel12.setBounds(160, 380, 140, 40);

        jTextField5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField5);
        jTextField5.setBounds(320, 390, 330, 30);

        jLabel9.setText("Price:");
        jLabel9.setBackground(new java.awt.Color(102, 255, 204));
        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 255, 204));
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 430, 50, 40);

        jTextField8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8);
        jTextField8.setBounds(320, 440, 330, 30);

        jButton1.setText("Update");
        jButton1.setBackground(new java.awt.Color(0, 0, 255));
        jButton1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 255, 204));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(280, 520, 130, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/upt.png"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(800, 600));
        jLabel1.setMinimumSize(new java.awt.Dimension(800, 600));
        jLabel1.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 800, 600);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        ManageTickets ob=new ManageTickets();
        ob.setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String a="",b="",c="",d="",e="",f="",g="",h="";
        a=jTextField1.getText().toString();
        b=jComboBox1.getSelectedItem().toString();
        c=jTextField3.getText().toString();
        d= ((JTextField)jDateChooser1.getDateEditor().getUiComponent()).getText();
        e=((JTextField)jDateChooser2.getDateEditor().getUiComponent()).getText();
        if(timePicker1.getText().contains("am")){
            String arr[]=timePicker1.getText().split(":");
            f=arr[0]+":"+(arr[1].replace("am",""))+":"+"00";
        }else if(timePicker1.getText().contains("pm")){
            String arr[]=timePicker1.getText().split(":");
            f=(12+Integer.parseInt(arr[0]))+":"+(arr[1].replace("pm",""))+":"+"00";
        }
        g=jTextField5.getText().toString();
        h=jTextField8.getText().toString();
        if(a.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter passenger id");
        }else if(b.equals("Choose Seat Type")){
            JOptionPane.showMessageDialog(null, "Please select seat type");
        }else if(c.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter seat number");
        }else if(d.equals("")){
            JOptionPane.showMessageDialog(null, "Please select issue date");
        }else if(e.equals("")){
            JOptionPane.showMessageDialog(null, "Please select journey date");
        }else if(f.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter departure time");
        }else if(g.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter route number");
        }else if(h.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter price");
        }else{
            try{
                PreparedStatement ps = connect.prepareStatement(
      "UPDATE ticket SET passengerID = ?, seatType = ?,seatNumber=?,issueDate=?,journeyDate=?,departureTime=?,routeNumber=?,price=? WHERE ticketID = ?");
                ps.setString(1,a);
                ps.setString(2,b);
                ps.setString(3,c);
                ps.setString(4,d);
                ps.setString(5,e);
                ps.setString(6,f);
                ps.setString(7,g);
                ps.setString(8,h);
                ps.setInt(9, id);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data updated successfully");
                ps.close();
                ManageTickets ob=new ManageTickets();
                ob.setVisible(true);
                dispose();
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "Cannot update in the database");
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdateData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdateData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField8;
    private com.github.lgooddatepicker.components.TimePicker timePicker1;
    // End of variables declaration//GEN-END:variables
}
